# 5. You are a student in a class of 10. Your class teacher assigns you a task of entering the
# names of all the students in the class. You finally want to display the names given the
# condition that the maximum allowed characters in a name is 15. As a fun task, reverse the
# names and display them. [Hint: Slicing works when you are selecting maximum characters]

names = []
for i in range(10):
    names.append(input(f"Enter the name of student {i+1}: "))
for name in names:
    print(name[:15][::-1])