let arr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ];
console.log(arr.length);
console.log(arr[4]);
arr.push(11);
console.log(arr);
arr.pop();
console.log(arr);
arr.shift();
console.log(arr);
arr.unshift(1);
console.log(arr);
arr.indexOf(5);
console.log(arr);
arr.includes(5);
let arr2 = [ 12, 13, 14, 15, 16, 17, 18, 19, 20 ];
console.log(arr.concat(arr2));
console.log(arr.join(" "));
console.log(arr.reverse());
console.log(arr.slice(2, 6));// t0 delete elements from array and add new elements
console.log(arr.sort());